import { useState, useEffect } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import ApiClient from "@/lib/apiClient";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Search,
  Activity,
  Loader2,
  Play,
  BarChart3,
  RefreshCcw,
} from "lucide-react";

// ─────────────────────────────────────────────────────────────────────────────
// NEW Scanner (V2) — same look & flow as the Scanner page but fires the NEW
// V2 API (/api/live-logs-v2/run-live-testing). Every signal generated by V2
// is tracked in the backend for daily accuracy evaluation, and the Accuracy
// tab here shows the daily WIN/LOSS report.
// URL: /new-scanner (intentionally NOT listed in the sidebar)
// ─────────────────────────────────────────────────────────────────────────────

interface Stock {
  _id?: string;
  Symbol: string;
  StockName: string;
  Range?: number;
  isWatchlist?: boolean;
}

const formatVal = (val: any): string => {
  if (val === undefined || val === null) return "-";
  const num = Number(val);
  if (isNaN(num)) return String(val);
  return Number.isInteger(num) ? num.toString() : parseFloat(num.toFixed(3)).toString();
};

// Same pastel background per symbol as Scanner page (cosmetic only)
const getColor = (symbol: string) => {
  const colors = [
    "#e3f2fd", "#fce4ec", "#e8f5e9", "#fff3e0", "#ede7f6", "#f3e5f5",
    "#e0f7fa", "#f1f8e9", "#fffde7", "#fbe9e7", "#edeef7", "#e6f3f8",
  ];
  const hash = symbol.split("").reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return colors[hash % colors.length];
};

const allowedSymbolsMapping: Record<string, string> = {
  NIFTY: "^NSEI",
  BANKNIFTY: "%5ENSEBANK",
  CNXFINANCE: "NIFTY_FIN_SERVICE.NS",
  "MIDCPNIFTY1!": "NIFTY_MID_SELECT.NS",
  M_M: "M&M.NS",
  M_MFIN: "M&MFIN.NS",
};

const statusBadgeClass: Record<string, string> = {
  WIN: "bg-green-100 text-green-700 border border-green-300",
  LOSS: "bg-red-100 text-red-700 border border-red-300",
  FLAT: "bg-gray-100 text-gray-700 border border-gray-300",
  PENDING: "bg-amber-100 text-amber-700 border border-amber-300",
  NO_DATA: "bg-slate-100 text-slate-500 border border-slate-300",
};

// Open the stock's chart on TradingView (same as Scanner page)
const openTv = (raw: string) => {
  const sym = (raw || "").replace(".NS", "");
  const tvUrl = `https://in.tradingview.com/chart/?symbol=NSE%3A${encodeURIComponent(sym)}`;
  window.open(tvUrl, "_blank", "noopener,noreferrer");
};

// Same date formatting as Scanner page popup
const formatDate = (timestamp: string) => {
  if (!timestamp) return "N/A";
  let date = new Date(timestamp);
  if (isNaN(date.getTime())) {
    // Backend sends en-IN locale strings like "16/6/2026, 11:46:08 am"
    // (DD/M/YYYY), which the Date constructor can't parse directly.
    const match = timestamp.match(
      /^(\d{1,2})\/(\d{1,2})\/(\d{4}),?\s*(\d{1,2}):(\d{2}):(\d{2})\s*(am|pm)$/i,
    );
    if (match) {
      const [, day, month, year, hour, minute, second, meridiem] = match;
      let h = parseInt(hour, 10) % 12;
      if (meridiem.toLowerCase() === "pm") h += 12;
      date = new Date(
        parseInt(year, 10),
        parseInt(month, 10) - 1,
        parseInt(day, 10),
        h,
        parseInt(minute, 10),
        parseInt(second, 10),
      );
    }
  }
  if (isNaN(date.getTime())) return timestamp;
  return date.toLocaleString("en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });
};

// Nested 5m / 15m interval detail block — same markup as Scanner page popup
const IntervalDetailBlock = ({ label, sig }: { label: string; sig: any }) => {
  if (!sig) return null;
  return (
    <div className="p-1.5 rounded bg-black/5 dark:bg-white/5 space-y-0.5 text-left">
      <div className="font-bold text-blue-850 dark:text-blue-400">⏱️ {label}</div>
      <div className="grid grid-cols-2 gap-x-2 text-[11px] opacity-90">
        <div>Open: <span className="font-semibold">{formatVal(sig.open)}</span></div>
        <div>Close: <span className="font-semibold">{formatVal(sig.close)}</span></div>
        <div>High: <span className="font-semibold">{formatVal(sig.high)}</span></div>
        <div>Low: <span className="font-semibold">{formatVal(sig.low)}</span></div>
        <div className="col-span-2 mt-0.5 border-t border-dashed border-slate-300 flex justify-between">
          <span>Sig H: <span className="font-bold text-blue-600 dark:text-blue-400">{formatVal(sig.signalHigh)}</span></span>
          <span>Sig L: <span className="font-bold text-amber-600 dark:text-amber-500">{formatVal(sig.signalLow)}</span></span>
        </div>
      </div>
      {sig.signalGeneratedAt && (
        <div className="text-[9px] opacity-75">📅 Generated: {sig.signalGeneratedAt}</div>
      )}
    </div>
  );
};

// One result item card inside the popup — same markup as Scanner page popup
const SignalItemCard = ({ item }: { item: any }) => (
  <div
    className="mb-2 sm:mb-3 p-2 sm:p-3 rounded-lg border border-gray-300 text-xs sm:text-sm"
    style={{ backgroundColor: getColor(item.symbol) }}
  >
    <div className="font-bold flex items-center gap-1 flex-wrap">
      <Button size="sm" variant="ghost" className="h-6 px-2" onClick={() => openTv(item.symbol)}>
        <img
          src="https://static.tradingview.com/static/images/favicon.ico"
          alt="TV"
          className="h-3 w-3 mr-1"
        />
      </Button>
      <span>
        {item.symbol} - Date: {formatDate(item.timestamp)}
      </span>
    </div>
    {item.signal5m || item.signal15m ? (
      <div className="space-y-1.5 mt-1.5 pt-1.5 border-t border-dashed border-gray-300 text-xs">
        {item.signal5m && <IntervalDetailBlock label="5 Min Interval" sig={item.signal5m} />}
        {item.signal15m && <IntervalDetailBlock label="15 Min Interval" sig={item.signal15m} />}
      </div>
    ) : (
      <>
        <div className="mt-1">
          Open: {formatVal(item.open)} | High: {formatVal(item.high)} | Low:{" "}
          {formatVal(item.low)} | Close: {formatVal(item.close)}
        </div>
        <div className="mt-1">
          Signal High: {formatVal(item.signalHigh)} | Signal Low: {formatVal(item.signalLow)}
        </div>
        {item.signalGeneratedAt && (
          <div className="mt-1 text-blue-600 font-medium">
            📅 Signal Generated: {item.signalGeneratedAt}
          </div>
        )}
      </>
    )}
  </div>
);

// RESPONSIVE RESULTS POPUP — same design as Scanner page's StockTable dialog
const ResultsDialog = ({
  isOpen,
  onClose,
  results,
  operationInterval,
}: {
  isOpen: boolean;
  onClose: () => void;
  results: any[];
  operationInterval: string[];
}) => {
  if (!isOpen) return null;

  const buyItems = results.filter((item) => item.type === "BUY");
  const sellItems = results.filter((item) => item.type === "SELL");

  return (
    <div
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-2 sm:p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-lg w-full max-w-xs sm:max-w-sm md:max-w-2xl lg:max-w-4xl xl:max-w-6xl max-h-[90vh] overflow-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex justify-between items-center p-3 sm:p-6 border-b">
          <h2 className="text-lg sm:text-2xl font-bold truncate pr-2">
            Signal Results (V2) -{" "}
            {operationInterval.includes("5m") && operationInterval.includes("15m")
              ? "5min+15min"
              : operationInterval.join(", ") || "Current Time Signals"}
          </h2>
          <Button variant="outline" onClick={onClose} size="sm" className="shrink-0">
            ✕ <span className="hidden sm:inline">Close</span>
          </Button>
        </div>
        <div className="p-3 sm:p-6">
          <div className="overflow-x-auto">
            <table className="w-full border-collapse min-w-[300px]">
              <thead>
                <tr className="bg-gray-100">
                  <th className="border p-2 sm:p-4 text-left font-semibold text-xs sm:text-sm">
                    Buy Signals
                  </th>
                  <th className="border p-2 sm:p-4 text-left font-semibold text-xs sm:text-sm">
                    Sell Signals
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border p-2 sm:p-4 align-top">
                    <div className="space-y-2">
                      {buyItems.length > 0 ? (
                        buyItems.map((item, index) => (
                          <SignalItemCard key={index} item={item} />
                        ))
                      ) : (
                        <div className="text-gray-500 text-center py-4 text-sm w-full">
                          No data
                        </div>
                      )}
                    </div>
                  </td>
                  <td className="border p-2 sm:p-4 align-top">
                    <div className="space-y-2">
                      {sellItems.length > 0 ? (
                        sellItems.map((item, index) => (
                          <SignalItemCard key={index} item={item} />
                        ))
                      ) : (
                        <div className="text-gray-500 text-center py-4 text-sm w-full">
                          No data
                        </div>
                      )}
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

// Summary stat block used in the accuracy report
const StatBox = ({ label, stats }: { label: string; stats: any }) => {
  if (!stats) return null;
  return (
    <div className="p-3 rounded-lg border bg-white shadow-sm">
      <div className="text-xs font-semibold text-gray-500 mb-1">{label}</div>
      <div className="text-lg font-bold">
        {stats.accuracyPct !== null && stats.accuracyPct !== undefined ? `${stats.accuracyPct}%` : "—"}
        <span className="text-xs font-normal text-gray-500 ml-1">accuracy</span>
      </div>
      <div className="text-xs text-gray-600 mt-1">
        Total {stats.total} · <span className="text-green-600 font-medium">W {stats.wins}</span> ·{" "}
        <span className="text-red-600 font-medium">L {stats.losses}</span> · Flat {stats.flat} · Pend {stats.pending}
      </div>
    </div>
  );
};

export default function NewScanner() {
  const [stocks, setStocks] = useState<Stock[]>([]);
  const [allStocks, setAllStocks] = useState<Stock[]>([]);
  const [checkedStocks, setCheckedStocks] = useState<Stock[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [scanning, setScanning] = useState(false);
  const [operationInterval, setOperationInterval] = useState<string[]>([]);
  const [candlesInterval, setCandlesInterval] = useState("15m");
  const [results, setResults] = useState<any[]>([]);
  const [hasScanned, setHasScanned] = useState(false);
  const [isPopupOpen, setIsPopupOpen] = useState(false);

  // Accuracy report states
  const [reportDate, setReportDate] = useState(new Date().toISOString().split("T")[0]);
  const [reportPeriod, setReportPeriod] = useState<"daily" | "weekly" | "monthly">("daily");
  const [report, setReport] = useState<any>(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [evaluating, setEvaluating] = useState(false);

  const intervalOptions = ["5m", "15m", "30m", "1h", "1d"];

  useEffect(() => {
    fetchStockList();
  }, []);

  const fetchStockList = async () => {
    setLoading(true);
    try {
      const allStocksData: Stock[] = await ApiClient.get("/api/stock/all");
      if (Array.isArray(allStocksData)) {
        setAllStocks(allStocksData);
        setStocks(allStocksData);
      } else {
        setAllStocks([]);
        setStocks([]);
        toast.error("No stocks data received from server.");
      }
    } catch (err) {
      setAllStocks([]);
      setStocks([]);
      toast.error("Failed to load stocks. Please check your connection and try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = (value: string) => {
    setSearchQuery(value);
    if (value === "") {
      setStocks(allStocks);
    } else {
      setStocks(
        allStocks.filter(
          (s) =>
            s.Symbol.toLowerCase().includes(value.toLowerCase()) ||
            s.StockName.toLowerCase().includes(value.toLowerCase()),
        ),
      );
    }
  };

  const handleStockSelection = (stock: Stock) => {
    const isSelected = checkedStocks.some((s) => s.Symbol === stock.Symbol);
    if (isSelected) {
      setCheckedStocks(checkedStocks.filter((s) => s.Symbol !== stock.Symbol));
    } else {
      setCheckedStocks([...checkedStocks, stock]);
    }
  };

  const handleSelectAll = (checked: boolean) => {
    setCheckedStocks(checked ? stocks : []);
  };

  const handleOperationCheckboxChange = (value: string) => {
    setOperationInterval((prev) =>
      prev.includes(value) ? prev.filter((v) => v !== value) : [...prev, value],
    );
  };

  // ── Fire the NEW V2 API ──
  const handleRunV2 = async () => {
    if (checkedStocks.length === 0) {
      toast.error("⚠️ Please select at least one stock.");
      return;
    }
    if (operationInterval.length === 0) {
      toast.error("⚠️ Please select operation time interval (5m / 15m).");
      return;
    }

    const symbols = checkedStocks.map(
      (item) => allowedSymbolsMapping[item.Symbol] || `${item.Symbol}.NS`,
    );

    setScanning(true);
    setResults([]);
    try {
      const data = await ApiClient.post("/api/live-logs-v2/run-live-testing", {
        symbols,
        interval: candlesInterval,
        operationInterval,
      });

      if (data && data.success) {
        setResults(data.data || []);
        setHasScanned(true);
        if (!data.data || data.data.length === 0) {
          toast.info("No BUY/SELL signals found for the selected stocks and intervals.");
        } else {
          // Show results in the same dialog style as the Scanner page
          setIsPopupOpen(true);
          toast.success(`✅ ${data.data.length} signal(s) found & saved for accuracy tracking.`);
        }
      } else {
        throw new Error(data?.message || "No data received from server");
      }
    } catch (error: any) {
      if (error.name !== "AbortError") {
        toast.error(`Scan Failed: ${error.message}`);
      }
    } finally {
      setScanning(false);
    }
  };

  // ── Accuracy report (daily / weekly / monthly) ──
  const loadReport = async (period?: "daily" | "weekly" | "monthly") => {
    const p = period || reportPeriod;
    setReportLoading(true);
    try {
      let data: any;
      if (p === "daily") {
        data = await ApiClient.get(`/api/accuracy/report?date=${reportDate}`);
      } else {
        // Weekly = last 7 days, Monthly = last 30 days (ending at reportDate)
        const to = new Date(reportDate);
        const from = new Date(to);
        from.setDate(to.getDate() - (p === "weekly" ? 6 : 29));
        const fromStr = from.toISOString().split("T")[0];
        const toStr = to.toISOString().split("T")[0];
        data = await ApiClient.get(`/api/accuracy/report-range?from=${fromStr}&to=${toStr}`);
      }
      if (data && data.success) {
        setReport({ ...data, period: p });
        const empty = p === "daily" ? !data.signals?.length : !data.summary?.total;
        if (empty) {
          toast.info("No signals recorded in this period. Run the V2 scanner first.");
        }
      } else {
        throw new Error(data?.message || "No report data");
      }
    } catch (error: any) {
      toast.error(`Report Failed: ${error.message}`);
    } finally {
      setReportLoading(false);
    }
  };

  const handleEvaluate = async () => {
    setEvaluating(true);
    try {
      const data = await ApiClient.post("/api/accuracy/evaluate", { date: reportDate });
      if (data && data.success) {
        toast.success(
          data.evaluated !== undefined
            ? `✅ Evaluated ${data.evaluated} signal(s) for ${data.date}`
            : data.message || "Evaluation done",
        );
        await loadReport();
      } else {
        throw new Error(data?.message || "Evaluation failed");
      }
    } catch (error: any) {
      toast.error(`Evaluate Failed: ${error.message}`);
    } finally {
      setEvaluating(false);
    }
  };

  return (
    <>
      {scanning && (
        <div className="fixed inset-0 z-50 bg-black/30 backdrop-blur-sm flex items-center justify-center">
          <div className="bg-white rounded-md shadow p-4 flex items-center gap-3">
            <Loader2 className="h-5 w-5 animate-spin" />
            <div className="text-sm font-medium">Processing... Please wait</div>
          </div>
        </div>
      )}

      {/* Results popup — same design as Scanner page's dialog */}
      <ResultsDialog
        isOpen={isPopupOpen}
        onClose={() => setIsPopupOpen(false)}
        results={results}
        operationInterval={operationInterval}
      />

      <div className="space-y-4 sm:space-y-6 p-2 sm:p-4 lg:p-6">
        {/* HEADER */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-4">
          <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold tracking-tight">
            🧪 New Scanner (V2) — Accuracy Tracked
          </h1>
          <Badge variant="outline" className="w-fit text-xs">
            Every signal is saved & evaluated daily after market close
          </Badge>
        </div>

        <Tabs defaultValue="scanner" className="w-full">
          <TabsList>
            <TabsTrigger value="scanner" className="gap-1">
              <Activity className="h-4 w-4" /> Scanner
            </TabsTrigger>
            <TabsTrigger value="accuracy" className="gap-1" onClick={() => !report && loadReport()}>
              <BarChart3 className="h-4 w-4" /> Accuracy Report
            </TabsTrigger>
          </TabsList>

          {/* ────────────────── SCANNER TAB ────────────────── */}
          <TabsContent value="scanner" className="space-y-4">
            {/* Controls */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base sm:text-lg">⚙️ Scan Controls</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex flex-col sm:flex-row gap-4 sm:items-end">
                  <div>
                    <Label className="text-xs sm:text-sm font-medium">Candle Interval</Label>
                    <div className="flex gap-2 mt-1 flex-wrap">
                      {intervalOptions.map((opt) => (
                        <Button
                          key={opt}
                          size="sm"
                          variant={candlesInterval === opt ? "default" : "outline"}
                          onClick={() => setCandlesInterval(opt)}
                        >
                          {opt}
                        </Button>
                      ))}
                    </div>
                  </div>

                  <div>
                    <Label className="text-xs sm:text-sm font-medium">Operation Time Interval</Label>
                    <div className="flex gap-4 mt-2">
                      {["5m", "15m"].map((interval) => (
                        <label key={interval} className="flex items-center gap-2 text-sm cursor-pointer">
                          <Checkbox
                            checked={operationInterval.includes(interval)}
                            onCheckedChange={() => handleOperationCheckboxChange(interval)}
                          />
                          {interval === "5m" ? "5 Min" : "15 Min"}
                        </label>
                      ))}
                    </div>
                  </div>

                  <Button
                    onClick={handleRunV2}
                    disabled={scanning}
                    className="bg-blue-600 hover:bg-blue-700 gap-1 sm:ml-auto"
                  >
                    {scanning ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}
                    Run Live Test (V2)
                  </Button>
                </div>
                <p className="text-xs text-gray-500">
                  Select 5m + 15m together for combined confirmation (both intervals must agree on BUY/SELL).
                </p>
              </CardContent>
            </Card>

            {/* Stock selection */}
            <Card>
              <CardHeader className="pb-2">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                  <CardTitle className="text-base sm:text-lg">
                    📋 Select Stocks{" "}
                    <span className="text-sm font-normal text-gray-500">
                      ({checkedStocks.length} selected / {stocks.length})
                    </span>
                  </CardTitle>
                  <div className="flex items-center gap-3">
                    <label className="flex items-center gap-2 text-sm cursor-pointer">
                      <Checkbox
                        checked={stocks.length > 0 && checkedStocks.length === stocks.length}
                        onCheckedChange={(c) => handleSelectAll(Boolean(c))}
                      />
                      Select All
                    </label>
                    <div className="relative">
                      <Search className="absolute left-2 top-2.5 h-4 w-4 text-gray-400" />
                      <Input
                        placeholder="Search stocks..."
                        value={searchQuery}
                        onChange={(e) => handleSearch(e.target.value)}
                        className="pl-8 h-9 w-48 sm:w-64"
                      />
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {loading ? (
                  <div className="flex items-center gap-2 text-sm text-gray-500 py-6 justify-center">
                    <Loader2 className="h-4 w-4 animate-spin" /> Loading stocks...
                  </div>
                ) : (
                  <ScrollArea className="h-64 sm:h-80 border rounded-md p-2">
                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-1">
                      {stocks.map((stock) => {
                        const isSelected = checkedStocks.some((s) => s.Symbol === stock.Symbol);
                        return (
                          <div
                            key={stock.Symbol}
                            onClick={() => handleStockSelection(stock)}
                            className={`p-2 rounded border text-xs cursor-pointer transition-colors flex items-center gap-2 ${
                              isSelected
                                ? "border-blue-400 bg-blue-50"
                                : "border-gray-200 hover:bg-accent/50"
                            }`}
                          >
                            <Checkbox checked={isSelected} className="pointer-events-none" />
                            <span className="font-medium truncate">{stock.Symbol}</span>
                          </div>
                        );
                      })}
                    </div>
                  </ScrollArea>
                )}
              </CardContent>
            </Card>

            {/* Results open in the popup dialog (same as Scanner page).
                This button lets the user reopen the last scan's results. */}
            {hasScanned && results.length > 0 && (
              <Button
                variant="outline"
                onClick={() => setIsPopupOpen(true)}
                className="w-full sm:w-auto"
              >
                📡 View Last Scan Results ({results.length})
              </Button>
            )}
          </TabsContent>

          {/* ────────────────── ACCURACY TAB ────────────────── */}
          <TabsContent value="accuracy" className="space-y-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base sm:text-lg">📊 Daily Signal Accuracy</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex flex-col sm:flex-row gap-3 sm:items-end flex-wrap">
                  <div>
                    <Label className="text-xs sm:text-sm font-medium">Period</Label>
                    <div className="flex gap-2 mt-1">
                      {(["daily", "weekly", "monthly"] as const).map((p) => (
                        <Button
                          key={p}
                          size="sm"
                          variant={reportPeriod === p ? "default" : "outline"}
                          onClick={() => {
                            setReportPeriod(p);
                            loadReport(p);
                          }}
                        >
                          {p === "daily" ? "Daily" : p === "weekly" ? "Weekly (7d)" : "Monthly (30d)"}
                        </Button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <Label className="text-xs sm:text-sm font-medium">
                      {reportPeriod === "daily" ? "Report Date" : "End Date"}
                    </Label>
                    <Input
                      type="date"
                      value={reportDate}
                      onChange={(e) => setReportDate(e.target.value)}
                      className="h-9 w-44 mt-1"
                    />
                  </div>
                  <Button
                    onClick={() => loadReport()}
                    disabled={reportLoading}
                    variant="outline"
                    className="gap-1"
                  >
                    {reportLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCcw className="h-4 w-4" />}
                    Load Report
                  </Button>
                  <Button
                    onClick={handleEvaluate}
                    disabled={evaluating}
                    className="bg-indigo-600 hover:bg-indigo-700 gap-1"
                  >
                    {evaluating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}
                    Evaluate Now
                  </Button>
                  <p className="text-xs text-gray-500 sm:ml-auto">
                    Auto-evaluation runs daily at 15:45 IST after market close.
                  </p>
                </div>

                {report && (
                  <>
                    {/* Summary stats */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3">
                      <StatBox
                        label={
                          report.period === "daily"
                            ? `OVERALL (${report.date})`
                            : `OVERALL (${report.from} → ${report.to})`
                        }
                        stats={report.summary}
                      />
                      <StatBox label="BUY Signals" stats={report.byType?.BUY} />
                      <StatBox label="SELL Signals" stats={report.byType?.SELL} />
                      <StatBox label="5 Min Interval" stats={report.byInterval?.["5m"]} />
                      <StatBox label="15 Min Interval" stats={report.byInterval?.["15m"]} />
                    </div>

                    {/* Weekly/Monthly: per-day accuracy breakdown */}
                    {report.period !== "daily" && (
                      <div className="overflow-x-auto border rounded-lg">
                        <table className="w-full text-xs sm:text-sm">
                          <thead>
                            <tr className="bg-gray-100 text-left">
                              <th className="p-2">Date</th>
                              <th className="p-2">Total</th>
                              <th className="p-2">Wins</th>
                              <th className="p-2">Losses</th>
                              <th className="p-2">Flat</th>
                              <th className="p-2">Pending</th>
                              <th className="p-2">Accuracy %</th>
                            </tr>
                          </thead>
                          <tbody>
                            {(report.byDate || []).length === 0 ? (
                              <tr>
                                <td colSpan={7} className="p-4 text-center text-gray-500">
                                  No signals recorded in this period.
                                </td>
                              </tr>
                            ) : (
                              report.byDate.map((d: any) => (
                                <tr key={d.date} className="border-t hover:bg-accent/30">
                                  <td className="p-2 font-medium whitespace-nowrap">{d.date}</td>
                                  <td className="p-2">{d.total}</td>
                                  <td className="p-2 text-green-700 font-medium">{d.wins}</td>
                                  <td className="p-2 text-red-700 font-medium">{d.losses}</td>
                                  <td className="p-2">{d.flat}</td>
                                  <td className="p-2">{d.pending}</td>
                                  <td className="p-2 font-bold">
                                    {d.accuracyPct !== null && d.accuracyPct !== undefined
                                      ? `${d.accuracyPct}%`
                                      : "—"}
                                  </td>
                                </tr>
                              ))
                            )}
                          </tbody>
                        </table>
                      </div>
                    )}

                    {/* Signals table (daily view only) */}
                    {report.period === "daily" && (
                    <div className="overflow-x-auto border rounded-lg">
                      <table className="w-full text-xs sm:text-sm">
                        <thead>
                          <tr className="bg-gray-100 text-left">
                            <th className="p-2">Symbol</th>
                            <th className="p-2">Int.</th>
                            <th className="p-2">Type</th>
                            <th className="p-2">Signal Time</th>
                            <th className="p-2">Entry</th>
                            <th className="p-2">Status</th>
                            <th className="p-2">Reason</th>
                            <th className="p-2">Max ↑%</th>
                            <th className="p-2">Max ↓%</th>
                            <th className="p-2">EOD %</th>
                          </tr>
                        </thead>
                        <tbody>
                          {(report.signals || []).length === 0 ? (
                            <tr>
                              <td colSpan={10} className="p-4 text-center text-gray-500">
                                No signals recorded on this date.
                              </td>
                            </tr>
                          ) : (
                            report.signals.map((sig: any) => (
                              <tr key={sig._id} className="border-t hover:bg-accent/30">
                                <td className="p-2 font-medium">{sig.symbol?.replace(".NS", "")}</td>
                                <td className="p-2">{sig.interval}</td>
                                <td className="p-2">
                                  <Badge className={sig.signalType === "BUY" ? "bg-green-600" : "bg-red-600"}>
                                    {sig.signalType}
                                  </Badge>
                                </td>
                                <td className="p-2 whitespace-nowrap">{sig.signalCandleTime}</td>
                                <td className="p-2">{formatVal(sig.entryPrice)}</td>
                                <td className="p-2">
                                  <span className={`px-2 py-0.5 rounded text-xs font-semibold ${statusBadgeClass[sig.status] || ""}`}>
                                    {sig.status}
                                  </span>
                                </td>
                                <td className="p-2 text-gray-600">{sig.resultReason || "—"}</td>
                                <td className="p-2 text-green-700">{sig.maxUpPct != null ? `${sig.maxUpPct.toFixed(2)}%` : "—"}</td>
                                <td className="p-2 text-red-700">{sig.maxDownPct != null ? `${sig.maxDownPct.toFixed(2)}%` : "—"}</td>
                                <td className={`p-2 font-medium ${sig.eodChangePct > 0 ? "text-green-700" : sig.eodChangePct < 0 ? "text-red-700" : ""}`}>
                                  {sig.eodChangePct != null ? `${sig.eodChangePct.toFixed(2)}%` : "—"}
                                </td>
                              </tr>
                            ))
                          )}
                        </tbody>
                      </table>
                    </div>
                    )}
                  </>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </>
  );
}
